Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/AppRolesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MvcBreadCrumbs;
using Rite.Software.Shepherdaid.DAL.SecurityEntities;

namespace Rite.Software.Shepherdaid.Web.Frontend
{
    public class AppRolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AppRoles
        [BreadCrumb(Clear =true, Label ="Application Roles")]
        public ActionResult Index()
        {
            try
            {
                var roles = db.AppRoles.Include(a => a.RankType);
                return View(roles.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }


        // GET: AppRoles/Create
        [BreadCrumb(Label = "Create Application Role")]
        public ActionResult Create()
        {
            try
            {
                ViewBag.RankTypeId = new SelectList(db.RankTypes, "Id", "Rank");
                return View();
            }
            catch (Exception ex)
            {

                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: AppRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,RankTypeId")] AppRole appRole)
        {
            try
            {
                appRole.Id = Guid.NewGuid().ToString();
                db.Roles.Add(appRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ViewBag.Error = ex.Message;
            }

            ViewBag.RankTypeId = new SelectList(db.RankTypes, "Id", "Rank", appRole.RankTypeId);
            return View(appRole);
        }

        // GET: AppRoles/Edit/5

        [BreadCrumb(Label = "Edit Application Role")]
        public ActionResult Edit(string id)
        {
            try
            {
                AppRole appRole = db.AppRoles.Find(id);
                ViewBag.RankTypeId = new SelectList(db.RankTypes, "Id", "Rank", appRole.RankTypeId);
                return View(appRole);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: AppRoles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,RankTypeId")] AppRole appRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(appRole).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Invalid model state.";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.RankTypeId = new SelectList(db.RankTypes, "Id", "Rank", appRole.RankTypeId);
            return View(appRole);
        }

        // GET: AppRoles/Delete/5
        public ActionResult Delete(string id)
        {
            try
            {
                AppRole appRole = db.AppRoles.Find(id);
                db.Roles.Remove(appRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/ChurchesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MvcBreadCrumbs;
using Rite.Software.Shepherdaid.DAL.SecurityEntities;

namespace Rite.Software.Shepherdaid.Web.Frontend.Controllers
{
    public class ChurchesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Churches
        [BreadCrumb(Clear = true, Label = "Church")]
        public ActionResult Index()
        {
            return View(db.Churches.ToList());
        }

        // GET: Churches/Create

        [BreadCrumb(Label = "Create Church")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Churches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,Email,Website,Phone1,Phone2")] Church church)
        {
            try
            {
                church.RecordedBy = User.Identity.Name;
                church.LastModifiedBy = User.Identity.Name;
                church.DateRecorded = DateTime.Now;
                church.LastDateModified = DateTime.Now;

                db.Churches.Add(church);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(church);
            }
        }

        // GET: Churches/Edit/5

        [BreadCrumb(Label = "Edit Church")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Church church = db.Churches.Find(id);
            if (church == null)
            {
                return HttpNotFound();
            }
            return View(church);
        }

        // POST: Churches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,Email,Website,Phone1,Phone2,RecordedBy,DateRecorded,LastModifiedBy,LastDateModified")] Church church)
        {
            if (ModelState.IsValid)
            {
                church.LastModifiedBy = User.Identity.Name;
                church.LastDateModified = DateTime.Now;

                db.Entry(church).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(church);
        }

        // GET: Churches/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Church church = db.Churches.Find(id);
                db.Churches.Remove(church);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Church()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/DioceseController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MvcBreadCrumbs;
using Rite.Software.Shepherdaid.DAL.SecurityEntities;

namespace Rite.Software.Shepherdaid.Web.Frontend.Controllers
{
    public class DioceseController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Diocese
        [BreadCrumb(Clear =true, Label ="Dioceses")]
        public ActionResult Index()
        {
            try
            {
                var dioceses = db.Dioceses.Include(d => d.Church);
                return View(dioceses.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Diocese/Create
        [BreadCrumb(Label = "Create Diocese")]
        public ActionResult Create()
        {
            try
            {
                ViewBag.ChurchId = new SelectList(db.Churches, "Id", "Name");
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Diocese/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ChurchId,Name,Address,Email,Website,Phone1,Phone2")] Diocese diocese)
        {
            try
            {
                diocese.RecordedBy = User.Identity.Name;
                diocese.DateRecorded = DateTime.Now;
                diocese.LastModifiedBy = User.Identity.Name;
                diocese.LastDateModified = DateTime.Now;

                db.Dioceses.Add(diocese);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            ViewBag.ChurchId = new SelectList(db.Churches, "Id", "Name", diocese.ChurchId);
            return View(diocese);
        }

        // GET: Diocese/Edit/5
        [BreadCrumb(Label = "Edit Diocese")]
        public ActionResult Edit(int id)
        {

            try
            {
                Diocese diocese = db.Dioceses.Find(id);
                ViewBag.ChurchId = new SelectList(db.Churches, "Id", "Name", diocese.ChurchId);
                return View(diocese);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Diocese/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ChurchId,Name,Address,Email,Website,Phone1,Phone2,RecordedBy,DateRecorded")] Diocese diocese)
        {
            try
            {
                diocese.LastModifiedBy = User.Identity.Name;
                diocese.LastDateModified = DateTime.Now;

                db.Entry(diocese).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.ChurchId = new SelectList(db.Churches, "Id", "Name", diocese.ChurchId);
            return View(diocese);
        }

        // GET: Diocese/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Diocese diocese = db.Dioceses.Find(id);
                db.Dioceses.Remove(diocese);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("Index");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/ParishesController.cs
using Rite.Software.Shepherdaid.DAL.SecurityEntities;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Rite.Software.Shepherdaid.Web.Frontend.Controllers
{
    public class ParishesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Parishes
        public ActionResult Index()
        {
            try
            {
                var parishes = db.Parishes.Include(p => p.Diocese);
                return View(parishes.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Parishes/Create
        public ActionResult Create()
        {
            try
            {
                //var dioceseList = (from x in db.Dioceses
                //                             select new Diocese
                //                             {
                //                                 Id = x.Id,
                //                                 //Name = x.Name + " (" + x.Church.Name + ")",
                //                             }).ToList();

                ViewBag.DioceseId = new SelectList(db.Dioceses, "Id", "Name");
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Parishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DioceseId,Name,Address,Email,Website,Phone1,Phone2")] Parish parish)
        {
            try
            {
                parish.RecordedBy = User.Identity.Name;
                parish.DateRecorded = DateTime.Now;
                parish.LastModifiedBy = User.Identity.Name;
                parish.LastDateModified = DateTime.Now;

                db.Parishes.Add(parish);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.DioceseId = new SelectList(db.Dioceses, "Id", "Name", parish.DioceseId);
            return View(parish);
        }

        // GET: Parishes/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                Parish parish = db.Parishes.Find(id);
                ViewBag.DioceseId = new SelectList(db.Dioceses, "Id", "Name", parish.DioceseId);
                return View(parish);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: Parishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DioceseId,Name,Address,Email,Website,Phone1,Phone2,RecordedBy,DateRecorded")] Parish parish)
        {
            try
            {
                parish.LastModifiedBy = User.Identity.Name;
                parish.LastDateModified = DateTime.Now;

                db.Entry(parish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.DioceseId = new SelectList(db.Dioceses, "Id", "Name", parish.DioceseId);
            return View(parish);
        }

        // GET: Parishes/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                Parish parish = db.Parishes.Find(id);
                db.Parishes.Remove(parish);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/SecurityController.cs
using MvcBreadCrumbs;
using System.Web.Mvc;

namespace Rite.Software.Shepherdaid.Web.Frontend.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security
        [BreadCrumb(Clear =true, Label ="Security")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/Shared/_Layout - Copy (2).cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Security</title>
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="container">
        <div class="navbar-light bg-primary mt-0 fixed-top">
            <h3 class="text-center my-title-text">[NAME OF INSTITUTION]</h3>
        </div>
    </div>
    <div class="container-fluid">

        <div class="navbar navbar-expand-sm navbar-light bg-light mt-5 fixed-top my-navbar">
            <div class="navbar offset-md-2 col-md-8">
                <a href="#" class="navbar-brand">SA</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#collape-menu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collape-menu">
                    <ul class="navbar nav list-unstyled">
                        
                        <li class="nav-item">
                            <a href="#" class="nav-link">Members</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" data-target="#setup-dropdown">
                                Setup
                            </a>
                            <div class="dropdown-menu" aria-labelledby="setup-dropdown">
                                <ul class="list-unstyled">
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageChurch))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Churches", "Index", "Churches")                                                                                                                        @*<a href="~/Views/Churches/Index.cshtml" class="dropdown-item">Manage Churches</a>*@
                                        </li>
                                    }
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageDiocese))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Dioceses", "Index", "Diocese")
                                        </li>
                                    }
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageParishes))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Parishes", "Index", "Parishes")
                                        </li>
                                    }

                                </ul>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" data-target="#security-dropdown">
                                Security
                            </a>
                            <div class="dropdown-menu" aria-labelledby="setup-dropdown">
                                <ul class="list-unstyled">
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageGroups))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Groups", "Index", "ApplicationGroups")
                                        </li>
                                    }
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageChurch))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Roles", "Index", "AppRoles")
                                        </li>
                                    }
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageChurch))
                                    {
                                        <li class="dropdown-item">
                                            @Html.ActionLink("Manage Users", "Index", "AppUsers")
                                        </li>
                                    }
                                    @if (User.IsInRole(Rite.Software.Shepherdaid.Roles.MySystemRole.ManageChurch))
                                    {
                                        <li class="dropdown-item">
                                        @Html.ActionLink("Enable Users", "Disabled", "AppUsers")</li>
                                    }                                    
                                </ul>
                            </div>
                        </li>
                    </ul>

                </div>
            </div>
        </div>

    </div>

    <div class="container body-content">
        <div class="breadcrumb-fixed d-none d-md-block">
            @Html.Raw(MvcBreadCrumbs.BreadCrumb.DisplayRaw())
        </div>
        <br />
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; 2012 - @DateTime.Now.Year - Shepherd Aid</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
</body>
</html>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Security</title>
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">

    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Security", "Index", "Security")</li>
                    <li>@Html.ActionLink("Members", "Index", "Members")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
</body>
</html>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/Shared/_Security.cshtml
@using Rite.Software.Shepherdaid.Roles
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-2">
        <ul>
            @if (User.IsInRole(MySystemRole.ManageChurch))
            {
                <li>@Html.ActionLink("Manage Churches", "Index", "Churches")</li>
            }
            @if (User.IsInRole(MySystemRole.ManageDiocese))
            {
                <li>@Html.ActionLink("Manage Dioceses", "Index", "Diocese")</li>
            }
            @if (User.IsInRole(MySystemRole.ManageParishes))
            {
                <li>@Html.ActionLink("Manage Parishes", "Index", "Parishes")</li>
            }
            @if (User.IsInRole(MySystemRole.ManageGroups))
            {
                <li>@Html.ActionLink("Manage Groups", "Index", "ApplicationGroups")</li>
            }
            @if (User.IsInRole(MySystemRole.ManageRoles))
            {
                <li>@Html.ActionLink("Manage Roles", "Index", "AppRoles")</li>
            }
            @if (User.IsInRole(MySystemRole.ManageUsers))
            {
                <li>@Html.ActionLink("Manage Users", "Index", "AppUsers")</li>
            }
            @if (User.IsInRole(MySystemRole.SuperAdmin))
            {
            <li>@Html.ActionLink("Enable Users", "Disabled", "AppUsers")</li>
        }

        </ul>
    </div>
    <div class="col-md-10">
        <div class="row breadcrumb-fixed">
            @Html.Raw(MvcBreadCrumbs.BreadCrumbs.Display())
        </div>
        @*main content area*@

        <div class="row">
            @section scripts{
                @RenderSection("scripts", required: false)
            }
            @RenderBody()
        </div>
    </div>
</div>