Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/ApplicationGroupsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MvcBreadCrumbs;
using Rite.Software.Shepherdaid.DAL.SecurityEntities;
using Rite.Software.Shepherdaid.Enums;
using Rite.Software.Shepherdaid.Roles;

namespace Rite.Software.Shepherdaid.Web.Frontend
{
    public class ApplicationGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationGroups
        [BreadCrumb(Clear = true, Label = "Application Groups")]
        public ActionResult Index()
        {
            try
            {
                var applicationGroups = db.ApplicationGroups.Where(x=>x.CanChange== true).Include(a => a.Parish);
                return View(applicationGroups.ToList());
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }


        // GET: ApplicationGroups/Create
        [BreadCrumb(Label = "Create Application Group")]
        public ActionResult Create()
        {
            try
            {
                ViewBag.ParishId = new SelectList(db.Parishes, "Id", "Name");
                return View();
            }
            catch (Exception ex)
            {

                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: ApplicationGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ParishId,Name")] ApplicationGroup applicationGroup)
        {
            try
            {
                applicationGroup.CanChange = true;
                applicationGroup.RecordedBy = User.Identity.Name;
                applicationGroup.DateRecorded = DateTime.Now;
                applicationGroup.LastModifiedBy = User.Identity.Name;
                applicationGroup.LastDateModified = DateTime.Now;

                db.ApplicationGroups.Add(applicationGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            ViewBag.ParishId = new SelectList(db.Parishes, "Id", "Name", applicationGroup.ParishId);
            return View(applicationGroup);
        }

        // GET: ApplicationGroups/Edit/5
        [BreadCrumb(Label = "Edit Application Group")]
        public ActionResult Edit(int id)
        {

            try
            {
                ApplicationGroup applicationGroup = db.ApplicationGroups.Find(id);
                ViewBag.ParishId = new SelectList(db.Parishes, "Id", "Name", applicationGroup.ParishId);
                return View(applicationGroup);
            }
            catch (Exception ex)
            {

                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // POST: ApplicationGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ParishId,Name,CanChange,RecordedBy,DateRecorded")] ApplicationGroup applicationGroup)
        {
            try
            {
                applicationGroup.LastModifiedBy = User.Identity.Name;
                applicationGroup.LastDateModified = DateTime.Now;

                db.Entry(applicationGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.ParishId = new SelectList(db.Parishes, "Id", "Name", applicationGroup.ParishId);
            return View(applicationGroup);
        }

        // GET: ApplicationGroups/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                ApplicationGroup applicationGroup = db.ApplicationGroups.Find(id);
                db.ApplicationGroups.Remove(applicationGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("Index");
            }
        }


        [BreadCrumb(Label = "Application Group Roles")]
        public ActionResult GroupRoles(int id)
        {
            try
            {
                TempData["id"] = id;
                return View();
            }
            catch (Exception)
            {

                return View();
            }
        }

        [ChildActionOnly]
        public PartialViewResult AvalaibleRolesPartial(int id)
        {
            try
            {
                //get all roles not assigned to this group
                var assignedGroupList = db.ApplicationGroupRoles.Where(x => x.ApplicationGroupId == id).Select(s => s.AppRoleId).ToList();
                var result = db.AppRoles.ToList();
                result = result.Where(x => !assignedGroupList.Contains(x.Id)).ToList();
                int rankTypeId = 0;
                if (User.IsInRole(MySystemRole.SuperAdmin))
                {
                    //roles remain as retrieved
                }
                else if (User.IsInRole(MySystemRole.ManageChurch))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ChurchAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageDiocese))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.DioceseAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageParishes))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ParishAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else
                {
                    ViewBag.Error = "User does not have rights to see roles";
                }
                return PartialView(result);
            }
            catch (Exception ex)
            {

                return PartialView();
            }
        }

        [ChildActionOnly]
        public PartialViewResult AssignedRolesPartial(int id)
        {
            try
            {
                //get all roles not assigned to this group
                var result = db.ApplicationGroupRoles.Where(x=>x.ApplicationGroupId == id).ToList();
                int rankTypeId = 0;
                if (User.IsInRole(MySystemRole.SuperAdmin))
                {
                    //roles remain as retrieved
                }
                else if (User.IsInRole(MySystemRole.ManageChurch))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ChurchAdminLevel);
                    result = result.Where(x => x.AppRole.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageDiocese))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.DioceseAdminLevel);
                    result = result.Where(x => x.AppRole.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageParishes))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ParishAdminLevel);
                    result = result.Where(x => x.AppRole.RankTypeId >= rankTypeId).ToList();
                }
                else
                {
                    ViewBag.Error = "User does not have rights to see roles";
                }
                return PartialView(result);
            }
            catch (Exception ex)
            {

                return PartialView();
            }
        }

        public ActionResult AddGroupRoles(string[] available)
        {
            int id = Convert.ToInt32(TempData["id"]);

            try
            {
                foreach (var item in available)
                {
                    ApplicationGroupRole applicationGroupRole = new ApplicationGroupRole()
                    {
                        AppRoleId = item,
                        ApplicationGroupId = id,
                        RecordedBy = User.Identity.Name,
                        DateRecorded = DateTime.Now,
                        LastModifiedBy = User.Identity.Name,
                        LastDateModified = DateTime.Now,
                    };
                    db.ApplicationGroupRoles.Add(applicationGroupRole);
                }

                //add the roles to all group members
                var groupMemberList = db.AppUsers.Where(x => x.ApplicationGroupId == id).ToList();
                foreach (var item in groupMemberList)
                {
                    foreach (var roleId in available)
                    {
                        int cnt = db.AppUserRoles.Where(x => x.UserId == item.Id && x.RoleId == roleId).Count();
                        if (cnt.Equals(0))
                        {
                            AppUserRole appUserRole = new AppUserRole()
                            {
                                RoleId = roleId,
                                UserId = item.Id,
                                RecordedBy = User.Identity.Name,
                                DateRecorded = DateTime.Now,

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/AssignedRolesPartial.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.ApplicationGroupRole>

<div class="container-fluid">
    <div class="col-md-12">
        <fieldset>
            <legend class="font-weight-bold">GROUP ASSIGNED ROLES </legend>

            @using (Html.BeginForm("RevokeGroupRoles", "ApplicationGroups"))
            {
                @Html.AntiForgeryToken()

                if (!ViewData.ModelState.IsValid)
                {
                    @Html.ValidationMessage("Error")
                }

                if (Model != null && Model.Count() > 0)
                {
                    <div class="">
                        <input type="submit" id="btn-revoke" name="btn-revoke" class="btn btn-outline-dark btn-block" value="Revoke" onclick="return confirm('This action will revoke the selected roles from the group and from all users to whom the roles are assinged.');" />
                    </div>
                    <div class="table-responsive">

                        <table id="ListTable" class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" name="check-all-assigned" id="check-all-assigned" value="0" title="select/deselect all" />
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.AppRole.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.AppRole.RankType.Rank)
                                    </th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>
                                            <div class="checkbox" id="div-assigned-item">
                                                <label>
                                                    <input type="checkbox"
                                                           name="assigned"
                                                           id="assigned"
                                                           value="@item.Id" />
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppRole.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppRole.RankType.Rank)
                                        </td>
                                    </tr>

                                }
                            </tbody>

                        </table>
                    </div>
                }

            }
        </fieldset>
    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/AvalaibleRolesPartial.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.AppRole>

<div class="container-fluid">
    <div class="col-md-12">

        <fieldset>
            <legend class="font-weight-bold">GROUP AVAILABLE ROLES</legend>

            @using (Html.BeginForm("AddGroupRoles", "ApplicationGroups"))
            {
                @Html.AntiForgeryToken()

                if (!ViewData.ModelState.IsValid)
                {
                    @Html.ValidationMessage("Error")
                }

                if (Model != null && Model.Count() > 0)
                {
                    <div>
                        <input type="submit" id="btn-assign" name="btn-assign" class="btn btn-outline-dark btn-block" value="Assign" onclick="return confirm('This action will assign the selected roles to the group.');" />
                    </div>

                    <div class="table-responsive">
                        <table id="ListTable" class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" name="check-all-available" id="check-all-available" value="0" title="select/deselect all" />
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.RankType.Rank)
                                    </th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>
                                            <div class="checkbox" id="div-available-item">
                                                <label>
                                                    <input type="checkbox"
                                                           name="available"
                                                           id="available"
                                                           value="@item.Id" />
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RankType.Rank)
                                        </td>
                                    </tr>

                                }
                            </tbody>

                        </table>
                    </div>
                }
            }
        </fieldset>
    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/Create.cshtml
@model Rite.Software.Shepherdaid.DAL.SecurityEntities.ApplicationGroup

@{
    ViewBag.Title = "Create Application Group";

}

<div class="container-fluid">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-row">
                    @Html.LabelFor(model => model.ParishId, htmlAttributes: new { @class = "text-left col-md-1" })
                    <div class="col-md-11">
                        @Html.DropDownList("ParishId", null, "--select--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ParishId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "text-left col-md-1" })
                    <div class="col-md-11">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-11">
                        <input type="submit" value="Create" class="btn btn-primary btn-block" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/Edit.cshtml
@model Rite.Software.Shepherdaid.DAL.SecurityEntities.ApplicationGroup

@{
    ViewBag.Title = "Edit Application Group";
}

<div class="container-fluid">

    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-row hidden">
                @Html.LabelFor(model => model.ParishId, htmlAttributes: new { @class = "text-left col-md-1" })
                <div class="col-md-11">
                    @Html.DropDownList("ParishId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ParishId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-row">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "text-left col-md-1" })
                <div class="col-md-11">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-row invisible">
                @Html.LabelFor(model => model.CanChange, htmlAttributes: new { @class = "text-left col-md-1" })
                <div class="col-md-11">
                    @Html.CheckBoxFor(model => model.CanChange, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CanChange, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-row">
                <div class="col-md-1">
                </div>
                <div class="col-md-11">
                    <input type="submit" value="Save" class="btn btn-primary btn-block" />
                </div>
            </div>

            <div class="form-row invisible">
                @Html.LabelFor(model => model.RecordedBy, htmlAttributes: new { @class = "text-left col-md-1" })
                <div class="col-md-11">
                    @Html.EditorFor(model => model.RecordedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RecordedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-row invisible">
                @Html.LabelFor(model => model.DateRecorded, htmlAttributes: new { @class = "text-left col-md-1" })
                <div class="col-md-11">
                    @Html.EditorFor(model => model.DateRecorded, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateRecorded, "", new { @class = "text-danger" })
                </div>
            </div>
        }
    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/GroupRoles.cshtml
@{
    ViewBag.Title = "Group Roles";
}

<div class="row">
    <div class="col-md-6">
        @*add avialble rolse partial*@
        @{Html.RenderAction("AvalaibleRolesPartial");}
    </div>

    <div class="col-md-6">
        @*add assigned roles partial*@
        @{Html.RenderAction("AssignedRolesPartial");}
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/check-role.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable({
                'columnDefs': [{

                    'targets': [0,], /* column index */

                    'orderable': false, /* true or false */

                }]
            });
        });
    </script>
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/ApplicationGroups/Index.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.ApplicationGroup>

@{
    ViewBag.Title = "Application Groups";
    int cnt = 0;
}
<div class="container-fluid">
    <div class="col-md-12">

        <p class="text-right">
            @Html.ActionLink(" ", "Create", new { }, new { @class = "fa fa-plus-square", @title = "create new" })
        </p>

        @if (Model != null && Model.Count() > 0)
        {
        <div class="table-responsive">
            <table id="ListTable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            No.
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Parish.Name)
                        </th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @string.Format("{0}.", ++cnt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Parish.Name)
                            </td>

                            <td class="text-center">
                                @Html.ActionLink(" ", "GroupRoles", new { id = item.Id }, new { @class = "fa fa-arrow-circle-right", @title = "assign roles" }) 
                                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit", @title = "edit" }) 
                                @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash text-danger", @title = "delete", @onclick = "return confirm('This action will delete this record.');" })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
        }
    </div>
</div>


@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable();
        });
    </script>
}