Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Controllers/AppUsersController.cs
using MvcBreadCrumbs;
using Rite.Software.Shepherdaid.Enums;
using Rite.Software.Shepherdaid.Roles;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using Rite.Software.Shepherdaid.DAL.SecurityEntities;

namespace Rite.Software.Shepherdaid.Web.Frontend.Controllers
{
    public class AppUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AppUsers
        [BreadCrumb(Clear = true, Label = "Application Users")]
        public ActionResult Index()
        {
            var users = db.AppUsers.Where(x => x.IsActive == true).Include(a => a.ApplicationGroup);
            return View(users.ToList());
        }

        // GET: AppUsers/Create
        [BreadCrumb(Label = "Create Application User")]
        public ActionResult Create()
        {
            ViewBag.ApplicationGroupId = new SelectList(db.ApplicationGroups, "Id", "Name");
            return View();
        }

        // POST: AppUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,FirstName,MiddleName,LastName,PhoneNumber,ApplicationGroupId")] AppUser appUser)
        {
            try
            {
                appUser.IsActive = true;
                appUser.UserName = appUser.Email;
                appUser.PasswordHash = Crypto.HashPassword("WillTriple3@church");
                appUser.SecurityStamp = DateTime.UtcNow.ToString("yyyyMMddHHmmssffff");
                appUser.RecordedBy = User.Identity.Name;
                appUser.DateRecorded = DateTime.Now;
                appUser.LastModifiedBy = User.Identity.Name;
                appUser.LastDateModified = DateTime.Now;

                db.Users.Add(appUser);
                db.SaveChanges();

                var groupRoles = db.ApplicationGroupRoles.Where(x => x.ApplicationGroupId == appUser.ApplicationGroupId).ToList();
                List<AppUserRole> appUserRoles = new List<AppUserRole>();
                foreach (var item in groupRoles)
                {
                    appUserRoles.Add(
                        new AppUserRole
                        {
                            RoleId = item.AppRoleId.ToString(),
                            UserId = appUser.Id,
                            RecordedBy = User.Identity.Name,
                            DateRecorded = DateTime.Now,
                            LastModifiedBy = User.Identity.Name,
                            LastDateModified = DateTime.Now
                        });
                }
                db.AppUserRoles.AddRange(appUserRoles);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                ViewBag.ApplicationGroupId = new SelectList(db.ApplicationGroups, "Id", "Name", appUser.ApplicationGroupId);
                return View(appUser);
            }

        }

        // GET: AppUsers/Edit/5
        [BreadCrumb(Label = "Edit Application User")]
        public ActionResult Edit(string id)
        {

            try
            {
                AppUser appUser = db.AppUsers.Find(id);

                ViewBag.ApplicationGroupId = new SelectList(db.ApplicationGroups, "Id", "Name", appUser.ApplicationGroupId);
                return View(appUser);
            }
            catch (Exception)
            {
                return View();
            }
        }

        // POST: AppUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,FirstName,MiddleName,LastName,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,IsActive,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,ApplicationGroupId,RecordedBy,DateRecorded")] AppUser appUser)
        {
            try
            {
                appUser.LastModifiedBy = User.Identity.Name;
                appUser.LastDateModified = DateTime.Now;

                db.Entry(appUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            ViewBag.ApplicationGroupId = new SelectList(db.ApplicationGroups, "Id", "Name", appUser.ApplicationGroupId);
            return View(appUser);
        }

        // GET: AppUsers/Delete/5
        public ActionResult Disable(string id)
        {
            try
            {
                AppUser appUser = db.AppUsers.Find(id);
                appUser.IsActive = false;
                appUser.LastModifiedBy = User.Identity.Name;
                appUser.LastDateModified = DateTime.Now;

                db.Entry(appUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("Index");
            }
        }
        public ActionResult Disabled()
        {
            var users = db.AppUsers.Where(x=>x.IsActive==false).Include(a => a.ApplicationGroup);
            return View(users.ToList());
        }
        public ActionResult Enable(string id)
        {
            try
            {
                AppUser appUser = db.AppUsers.Find(id);
                appUser.IsActive = true;
                appUser.LastModifiedBy = User.Identity.Name;
                appUser.LastDateModified = DateTime.Now;
                db.Entry(appUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Disabled");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("Disabled");
            }
        }

        [BreadCrumb(Label = "Application User Roles")]
        public ActionResult UserRoles(string id)
        {
            try
            {
                TempData["id"] = id;
                return View();
            }
            catch (Exception)
            {

                return View();
            }
        }

        [ChildActionOnly]
        public PartialViewResult AvalaibleRolesPartial(string id)
        {
            try
            {
                //get all roles not assigned to this group
                var assignedGroupList = db.AppUserRoles.Where(x => x.UserId == id).Select(s => s.RoleId).ToList();
                var result = db.AppRoles.ToList();
                result = result.Where(x => !assignedGroupList.Contains(x.Id)).ToList();
                int rankTypeId = 0;
                if (User.IsInRole(MySystemRole.SuperAdmin))
                {
                    //roles remain as retrieved
                }
                else if (User.IsInRole(MySystemRole.ManageChurch))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ChurchAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageDiocese))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.DioceseAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageParishes))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ParishAdminLevel);
                    result = result.Where(x => x.RankTypeId >= rankTypeId).ToList();
                }
                else
                {
                    ViewBag.Error = "User does not have rights to see roles";
                }
                return PartialView(result);
            }
            catch (Exception)
            {

                return PartialView();
            }
        }

        [ChildActionOnly]
        public PartialViewResult AssignedRolesPartial(string id)
        {
            try
            {
                //get all roles not assigned to this user
                var roleList = db.AppUserRoles.Where(x => x.UserId == id).ToList();
                List<AppUserRole> result = new List<AppUserRole>();
                foreach (var item in roleList)
                {
                    item.AppRole = db.AppRoles.Find(item.RoleId);
                    result.Add(item);
                }
                int rankTypeId = 0;
                if (User.IsInRole(MySystemRole.SuperAdmin))
                {
                    //roles remain as retrieved
                }
                else if (User.IsInRole(MySystemRole.ManageChurch))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ChurchAdminLevel);
                    result = result.Where(x => x.AppRole.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageDiocese))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.DioceseAdminLevel);
                    result = result.Where(x => x.AppRole.RankTypeId >= rankTypeId).ToList();
                }
                else if (User.IsInRole(MySystemRole.ManageParishes))
                {
                    rankTypeId = Convert.ToInt32(MyEnums.RankType.ParishAdminLevel);

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/AssignedRolesPartial.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.AppUserRole>

<div class="container-fluid">

    <div class="col-md-12">
        <fieldset>
            <legend>USER ASSIGNED ROLES </legend>
            @using (Html.BeginForm("RevokeUserRoles", "AppUsers"))
            {
                @Html.AntiForgeryToken()

                if (!ViewData.ModelState.IsValid)
                {
                    @Html.ValidationMessage("Error")
                }

                if (Model != null && Model.Count() > 0)
                {
                    <div>
                        <input type="submit" id="btn-revoke" name="btn-revoke" class="btn btn-outline-dark btn-block" value="Revoke" onclick="return confirm('This action will revoke the selected roles from the group and from all users to whom the roles are assinged.');" />
                    </div>
                    <div class="table-responsive">

                        <table id="ListTable" class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" name="check-all-assigned" id="check-all-assigned" value="0" title="select/deselect all" />
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.AppRole.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.AppRole.RankType.Rank)
                                    </th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>
                                            <div class="checkbox" id="div-assigned-item">
                                                <label>
                                                    <input type="checkbox"
                                                           name="assigned"
                                                           id="assigned"
                                                           value="@item.RoleId" />
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppRole.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppRole.RankType.Rank)
                                        </td>
                                    </tr>

                                }
                            </tbody>

                        </table>
                    </div>
                }

            }
        </fieldset>
    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/AvalaibleRolesPartial.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.AppRole>

<div class="container-fluid">

    <div class="col-md-12">
        <fieldset>
            <legend>USER AVAILABLE ROLES </legend>
            @using (Html.BeginForm("AddUserRoles", "AppUsers"))
            {
                @Html.AntiForgeryToken()

                if (!ViewData.ModelState.IsValid)
                {
                    @Html.ValidationMessage("Error")
                }

                if (Model != null && Model.Count() > 0)
                {
                    <div class="">
                        <input type="submit" id="btn-assign" name="btn-assign" class="btn btn-outline-dark btn-block" value="Assign" onclick="return confirm('This action will assign the selected roles to the group.');" />
                    </div>

                    <div class="table-responsive">
                        <table id="ListTable" class="table table-bordered table-striped table-responsive">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" name="check-all-available" id="check-all-available" value="0" title="select/deselect all" />
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.RankType.Rank)
                                    </th>

                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>
                                            <div class="checkbox" id="div-available-item">
                                                <label>
                                                    <input type="checkbox"
                                                           name="available"
                                                           id="available"
                                                           value="@item.Id" />
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.RankType.Rank)
                                        </td>
                                    </tr>

                                }
                            </tbody>

                        </table>
                    </div>
                }

            }
        </fieldset>
    </div>

</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/Create.cshtml
@model Rite.Software.Shepherdaid.DAL.SecurityEntities.AppUser

@{
    ViewBag.Title = "Create User";
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-body">
            <div class="col-md-12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <div class="form-row">
                            @Html.LabelFor(model => model.ApplicationGroupId, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ApplicationGroupId", null, "--select--", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ApplicationGroupId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-row">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-row">
                            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-row">
                            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-row">
                            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-row">
                            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "text-right col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-row">
                                @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "text-right col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.TwoFactorEnabled)
                                        @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>*@

                        <div class="form-row">
                            <div class="col-md-2">
                            </div>
                            <div class="col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary btn-block" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/Disabled.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.AppUser>

@{
    ViewBag.Title = "Disabled Users";
    int cnt = 0;
}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-body">
            <div class="col-md-12">

                @if (Model != null && Model.Count() > 0)
                {
                <div class="table-responsive">
                    <table id="ListTable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    No.
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FirstName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MiddleName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.LastName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UserName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ApplicationGroup.Name)
                                </th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @string.Format("{0}.", ++cnt)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MiddleName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LastName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ApplicationGroup.Name)
                                    </td>

                                    <td class="text-center">
                                        @Html.ActionLink(" ", "Enable", new { id = item.Id }, new { @class = "fa fa-play-circle", @onclick = "return confirm('This action will enable this user.');", @title = "enable" })
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>

                </div>
                }
            </div>
        </div>
    </div>
</div>


@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable();
        });
    </script>
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/Index.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.AppUser>

@{
    ViewBag.Title = "App Users";
    int cnt = 0;
}

<div class="container-fluid">
    <div class="col-md-12">

        <p class="text-right">
            @Html.ActionLink(" ", "Create", new { }, new { @class = "fa fa-plus-square", @title = "create new" })
        </p>

        @if (Model != null && Model.Count() > 0)
        {
            <div class="table-responsive">
                <table id="ListTable" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                No.
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.MiddleName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.UserName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApplicationGroup.Name)
                            </th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @string.Format("{0}.", ++cnt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MiddleName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationGroup.Name)
                                </td>

                                <td class="text-center">
                                    @Html.ActionLink(" ", "Transfer", new { id = item.Id }, new { @class = "fa fa-random", @title = "transfer" })
                                    @Html.ActionLink(" ", "UserRoles", new { id = item.Id }, new { @class = "fa fa-arrow-circle-right", @title = "assign roles" })
                                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit", @title = "edit" })
                                    @Html.ActionLink(" ", "Disable", new { id = item.Id }, new { @class = "fa fa-power-off text-danger", @title = "disable", @onclick = "return confirm('This action will disable this record.');" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        }
    </div>
</div>


@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable();
        });
    </script>
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/Transfer.cshtml
@model IEnumerable<Rite.Software.Shepherdaid.DAL.SecurityEntities.ApplicationGroup>

@{
    ViewBag.Title = "Transfer User";
    int cnt = 0;
}

<div class="container-fluid">
    <div class="col-md-12">

        @if (Model != null && Model.Count() > 0)
        {

            <table id="ListTable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            No.
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.CanChange)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @string.Format("{0}.", ++cnt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td class="text-center">
                                @Html.DisplayFor(modelItem => item.CanChange)
                            </td>
                            <td class="text-center">
                                @Html.ActionLink(" ", "TransferUser", new { id = item.Id }, new { @class = "fa fa-random", @title = "transfer to this group" })
                            </td>
                        </tr>
                    }

                </tbody>

            </table>

        }
    </div>
</div>


@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable();
        });
    </script>
}

Rite.Software.Shepherdaid.Web.Frontend/Rite.Software.Shepherdaid.Web.Frontend/Views/AppUsers/UserRoles.cshtml
@{
                /**/

                ViewBag.Title = "Group Roles";
}

<div class="row">
    <div class="col-md-6">
        @*add avialble rolse partial*@
        @{Html.RenderAction("AvalaibleRolesPartial");}
    </div>


    <div class="col-md-6">
        @*add assigned roles partial*@
        @{Html.RenderAction("AssignedRolesPartial");}
    </div>
</div>
@section Scripts{

    <script src="~/Scripts/check-role.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ListTable').DataTable({
                'columnDefs': [{

                    'targets': [0,], /* column index */

                    'orderable': false, /* true or false */

                }]
            });
        });
    </script>
}